name: Docker Build and Push

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]  # 기존 CI/CD 파이프라인 워크플로우 이름을 맞춰주세요.
    types:
      - completed  # CI/CD Pipeline이 완료되면 이 워크플로우가 트리거됨

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Action에서 사용할 환경 설정

    steps:
      # 깃허브 저장소에서 소스 코드 가져옴
      - name: Checkout Code
        uses: actions/checkout@v3

      # Java 17 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'